import QueryProvider from "@/components/QueryProvider";
import { Analytics } from "@/components/analytics";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-inter",
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={cn(
        "font-sans bg-dark text-slate-900 antialiased",
        fontSans.variable
      )}>
      <body className="min-h-screen">
        <QueryProvider>
          {children}
        </QueryProvider>

        {/* <Analytics /> */}
      </body>
    </html>
  );
}
